### ISSUE TITLE
Linux cannot install phenofit

### ISSUE THREAD

**Issue by Hisschao** [eco-hydro/phenofit#12]
The phenofit package of the lunix system configuration is missing ipaper and sf2. How can I install ipaper and sf2? What is the version of R? Are there any specific installation steps

**Comment by kongdd** [comment]
`phenofit` did not rely on Ipaper and sf2. It is `phenofit-scripts`:
Please read the README.md first
https://github.com/eco-hydro/phenofit-scripts#installation
