### ISSUE TITLE
What is the reason for the stripes in both the generated fit image and pheno image?

### ISSUE THREAD

**Issue by weichow12318** [eco-hydro/phenofit#15]
Hello, Professor!

I am trying to generate the phenology image of the Yangtze River Delta region, using the same parameter of HeNan Example, but the generated phenology image always has stripes, and sometimes can't generate the full image. I also tried to generate the vegetation index after fine fitting, but also stripes. 

I think there should be a problem in fitting the interpolated values, but I don't know which parameters are the most critical factors affecting such problems and how to change the parameters to solve it. May you help me about this?

The following figure is a phenology map and fitted map according to the following code (similar to the HeNan example) of a small county in Anhui Province.
![fit](https://github.com/eco-hydro/phenofit/assets/145658586/176e57ec-092b-410d-9bd8-9ff899631378)
![pheno](https://github.com/eco-hydro/phenofit/assets/145658586/7ef187e1-9906-4e2b-b699-9afd871728f1)
![code](https://github.com/eco-hydro/phenofit/assets/145658586/bdfffe00-ce00-44b2-b7b1-5c3e1d144dcf)

**Comment by kongdd** [comment]
- 看图的样子，应该是空间数据的排序出现了问题，而非phenofit的错误。你对空间数据操作是否熟练？可以尝试做个简单的计算，如多年平均VI，看空间图是否正确。

- 河南省的样例数据能跑通吗？

**Comment by weichow12318** [comment]
老师您好！
        谢谢老师的指导！我之前的fit影像忘记与坐标数据匹配Id了，所以出现了排列错误的问题。重新运行的如下所示。发现fit和pheno影像一样均存在条纹和无法绘全的问题。
       我在原来代码的基础上计算了VI的平均值影像，得到的是对的，和GEE运行出来的VI均值影像结果相同，所以我想应该不是读取数据和转换栅格的问题了。跑了河南省的样例数据也存在条带现象。但其实之前用相同代码跑过整个安徽省，发现如果运行整个省，条带非常严重，但如果将一个省其划分成十几块，就不会出现条带现象。但现在我用原来的已经划分的小块重新跑时，条带又出现了。

虽然基本依据的是样例代码，但真正运行时会有报错，因此根据报错内容修改了一小部分代码。
包括select_fist_nGS中（下面注释部分是原来代码）
if (length(inds_bad) == 0) {
    # return(df %>% select(-I, -TRS5.los))
    return(df %>% select(-I))
  }
并行运算时（增加了.packages)
t = system.time({
    res = foreach(i = inds %>% set_names(., .), icount(),
                  # )
    .packages = c("Ipaper", "phenofit","ggplot2","grid","dplyr")) %dopar% {
![Fit](https://github.com/eco-hydro/phenofit/assets/145658586/cbbd40ed-a03d-48ce-a19a-6db0109521ad)
![Pheno](https://github.com/eco-hydro/phenofit/assets/145658586/2dc169bb-f67e-4e7e-8f54-1fd48f58a3d0)
![henanEOS](https://github.com/eco-hydro/phenofit/assets/145658586/2a392831-2f98-4c1e-a24e-6c8466874334)

**Comment by kongdd** [comment]
issue请转移到<https://github.com/eco-hydro/phenofit-scripts>，这不是phenofit的bug。

另外，若想帮你解决问题，请提供一个可以重现错误的完整脚本。
