### ISSUE TITLE
can't install phenofit package in RStudio version 3.5.1

### ISSUE THREAD

**Issue by Gaohq123** [eco-hydro/phenofit#7]
I tried many ways to install your package in R,  but all failed.
I want to konw how to solve it.
![1544948876 1](https://user-images.githubusercontent.com/36120392/50051555-bad3d600-014f-11e9-8e04-166949930b05.jpg)

**Comment by kongdd** [comment]
1. I think this the problem of CRAN mirror. 
2. By the way, you need to install `rtools` first (https://cran.r-project.org/bin/windows/Rtools/).

Then, have a try about the following script:
```r
devtools::install_github('kongdd/phenofit', ref='gee_Whittaker')
```

**Comment by kongdd** [comment]
solved
